ekf_odom_node:
  ros__parameters:
    use_sim_time: true
    frequency: 50.0
    sensor_timeout: 0.5
    two_d_mode: true
    publish_tf: false

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # WHEEL ODOM: sadece vx kullan
    odom0: /wheel/odometry
    odom0_queue_size: 10
    odom0_nodelay: true
    odom0_differential: false
    odom0_relative: false
    odom0_pose_rejection_threshold: 5.0
    odom0_twist_rejection_threshold: 2.0
    # [x y z roll pitch yaw  vx vy vz vroll vpitch vyaw ax ay az]
    odom0_config: [false,false,false, false,false,false,
                   true, false,false, false,false,false,
                   false,false,false]

    # IMU: sadece yaw rate (angular z)
    imu0: /imu/data
    imu0_queue_size: 50
    imu0_nodelay: true
    imu0_differential: false
    imu0_relative: false
    imu0_remove_gravitational_acceleration: true
    imu0_config: [false,false,false,
                  false,false,false,
                  false,false,false,
                  false,false,true,
                  false,false]
